<a href="https://colab.research.google.com/github/Soumee06/assignments/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The first thing we want to do is import numpy.

In [1]:
import numpy as np

Let us first define a Python list containing the ages of 6 people.

In [2]:
ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use `np.array(<collection>)`

In [3]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [4]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [5]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


### Multi-dim

Now let us define a new list containing the weights of these 6 people.

In [6]:
weight_list = [32, 18, 26, 60, 55, 65]

Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.

In [7]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [8]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1 

people = people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)


###### Note: The new shape must be the same "size" as the old shape

### Exercise

* Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

* Generate a matrix (2D numpy array) of the values:

\begin{align}
  \mathbf{A} =
  \begin{pmatrix}
    1 & 2 & 4 \\
    2 & 3 & 0 \\
    0 & 5 & 1
  \end{pmatrix}
\end{align}

* Change the dimensions of this array to another permitted shape

In [9]:
array_list=[7,9,65,33,85,99]
array=np.array(array_list)

In [10]:
array

array([ 7,  9, 65, 33, 85, 99])

In [18]:
my_mat=[[1,2,4],[2,3,0],[0,5,1]]

In [89]:
arr2=np.array(my_mat)

In [90]:
arr2

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [91]:
arr2.reshape(9,1)

array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

## Array Generation

Instead of defining an array manually, we can ask numpy to do it for us.

The `np.arange()` method creates a range of numbers with user defined steps between each.

In [11]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

The `np.linspace()` method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [12]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The `.repeat()` method will repeat an object you pas a specified number of times.

In [13]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


The `np.eye()` functions will create an identity matrix/array for us.

In [14]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Operations

There are many, many operations which we can perform on arrays. Below, we demonstrate a few.

What is happening in each line?

In [15]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [16]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


### Speed Test

If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [17]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [20]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [21]:
%timeit five_times_table_lge + 5

1.3 µs ± 9.17 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
%timeit [e + 5 for e in fives_list]

59.3 µs ± 714 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Boolean string operations can also be performed on ndarrays.

In [23]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

# Transpose

In [24]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


# Data Types

As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the `.dtype` attribute.

In [25]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [26]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

What is the dtype of this array?

In [27]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

What do you think has happened here?

In [28]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [29]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [30]:
ages_with_strings.size

126

In [31]:
ages_with_strings.size/21

6.0

In [32]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the `.astype()` method, demonstrated below.

In [33]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


### Exercise

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

In [34]:
num_with_strings = np.array(['6','3','32', '65', '43'], dtype='float')

In [35]:
num_with_strings

array([ 6.,  3., 32., 65., 43.])

In [92]:
num_with_strings.astype(bool)

array([ True,  True,  True,  True,  True])

## Array Slicing Operations

As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [36]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [37]:
five_times_table[0]

0

In [38]:
five_times_table[-1]

50

In [39]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [40]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [41]:
print(people)
people[:3, :3]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

### Exercise

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

In [43]:
#numpy array with 50 zeros
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
#np array of 2 repeated 20 times
np.ones(20)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2.])

In [49]:
np.arange(0,2*22/7 ,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [50]:
s=np.arange(0,2*22/7 ,0.1)

In [52]:
s[0:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [57]:
s[-3: ]

array([6. , 6.1, 6.2])

In [59]:
s[3:7]

array([0.3, 0.4, 0.5, 0.6])

We can reverse an array by using `.flip()` or by using the `::` operator.

In [60]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [61]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

We can also use the `::` operator to select steps of the original array.

In [62]:
five_times_table[0::3] #Every 3rd element starting from 0

array([ 0, 15, 30, 45])

### Exercise
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

In [82]:
new_list=[3,6,9,12,15,18,21,24,27,30,33,36,39,42]
new_array=np.array(new_list)

In [83]:
new_array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [84]:
reverse_new_array=np.flip(new_list)
reverse_new_array

array([42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [85]:
new_array[0::4]

array([ 3, 15, 27, 39])

In [86]:
new_array[::2]

array([ 3,  9, 15, 21, 27, 33, 39])

# Stats

In [63]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [64]:
nums = np.arange(0, 4, 0.2555)

### Exercise

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [65]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


## Random

With `np.random`, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [66]:
flip = np.random.choice([0,1], 10)
flip

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1])

In [67]:
np.random.rand(10,20,9)

array([[[0.63231807, 0.40733813, 0.99635527, ..., 0.70192807,
         0.04641241, 0.19047734],
        [0.08446514, 0.53836288, 0.12226674, ..., 0.06113701,
         0.80572448, 0.48205002],
        [0.17812364, 0.45775882, 0.40634305, ..., 0.83070348,
         0.23725934, 0.82683899],
        ...,
        [0.83554315, 0.11031959, 0.42656202, ..., 0.43848099,
         0.3716995 , 0.8956877 ],
        [0.59536517, 0.69176522, 0.34023983, ..., 0.58841492,
         0.31144308, 0.23450958],
        [0.48876646, 0.75970358, 0.40780216, ..., 0.58886918,
         0.66009594, 0.17027977]],

       [[0.1593834 , 0.42681816, 0.30930991, ..., 0.81156043,
         0.25677317, 0.44687593],
        [0.31969483, 0.83444145, 0.69516597, ..., 0.6272341 ,
         0.02821805, 0.71786436],
        [0.10355008, 0.60578736, 0.14101291, ..., 0.06167782,
         0.15344092, 0.03327914],
        ...,
        [0.42353295, 0.39368358, 0.62615183, ..., 0.2799923 ,
         0.6928253 , 0.532865  ],
        [0.8

We can produce 1000 datapoints of a normally distributed data set by using `np.random.normal()`

In [68]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

### Exercise
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.


In [70]:
throw_dice= np.random.choice([1,2,3,4,5,6], 10)
throw_dice

array([2, 2, 6, 6, 1, 4, 4, 1, 4, 4])

In [71]:
toss=np.random.choice([0,1,1],10)

In [72]:
toss

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 1])